export type ClientCategory =
  | "all"
  | "energy"
  | "government"
  | "private-sector"
  | "property"
  | "transportation";

export interface ClientLogo {
  id: string;
  name: string;
  category: ClientCategory;
  src: string;
}

export const clientCategories: { id: ClientCategory; label: string }[] = [
  { id: "all", label: "All Clients" },
  { id: "energy", label: "Energy" },
  { id: "government", label: "Government" },
  { id: "private-sector", label: "Private Sector" },
  { id: "property", label: "Property" },
  { id: "transportation", label: "Transportation" },
];

export const clientLogos: ClientLogo[] = [
  {
    id: "birubatt-01",
    name: "BiruBatt 01",
    category: "energy",
    src: "/clients/energy/BiruBatt_Logo_01.avif",
  },
  {
    id: "birubatt-02",
    name: "BiruBatt 02",
    category: "energy",
    src: "/clients/energy/BiruBatt_Logo_02.avif",
  },
  {
    id: "delta",
    name: "DELTA",
    category: "energy",
    src: "/clients/energy/DELTA_Logo.avif",
  },
  {
    id: "ekt",
    name: "EKT",
    category: "energy",
    src: "/clients/energy/EKT_Logo.avif",
  },
  {
    id: "energy-equity",
    name: "Energy Equity",
    category: "energy",
    src: "/clients/energy/Energy_Equity_Logo.avif",
  },
  {
    id: "ev-power",
    name: "EV Power",
    category: "energy",
    src: "/clients/energy/EV_Power_Logo.avif",
  },
  {
    id: "jawa-satu-power",
    name: "Jawa Satu Power",
    category: "energy",
    src: "/clients/energy/Jawa_Satu_Power_Logo.avif",
  },
  {
    id: "karimun-power",
    name: "Karimun Power",
    category: "energy",
    src: "/clients/energy/Karimun_Power_Logo.avif",
  },
  {
    id: "lotte-chemical",
    name: "Lotte Chemical",
    category: "energy",
    src: "/clients/energy/Lotte_Chemical_Logo.avif",
  },
  {
    id: "mind-id",
    name: "MIND ID",
    category: "energy",
    src: "/clients/energy/MIND_ID_Logo.avif",
  },
  {
    id: "pertamina",
    name: "Pertamina",
    category: "energy",
    src: "/clients/energy/Pertamina_Logo.avif",
  },
  {
    id: "pjb",
    name: "PJB",
    category: "energy",
    src: "/clients/energy/PJB_Logo.avif",
  },
  {
    id: "pln-es",
    name: "PLN ES",
    category: "energy",
    src: "/clients/energy/PLN_ES_Logo.avif",
  },
  {
    id: "pln-01",
    name: "PLN",
    category: "energy",
    src: "/clients/energy/PLN_Logo_01.avif",
  },
  {
    id: "pln-greyscale",
    name: "PLN Greyscale",
    category: "energy",
    src: "/clients/energy/PLN_Logo_Greyscale.avif",
  },
  {
    id: "hengjaya-mineralindo",
    name: "PT Hengjaya Mineralindo",
    category: "energy",
    src: "/clients/energy/PT_Hengjaya_Mineralindo.avif",
  },
  {
    id: "yasa-artha-trimanunggal",
    name: "PT Yasa Artha Trimanunggal",
    category: "energy",
    src: "/clients/energy/PT_Yasa_Artha_Trimanunggal.avif",
  },
  {
    id: "aruna-hijau-power",
    name: "PT Aruna Hijau Power",
    category: "energy",
    src: "/clients/energy/PT._Aruna_Hijau_Power.avif",
  },
  {
    id: "carsurin",
    name: "PT Carsurin 1968",
    category: "energy",
    src: "/clients/energy/PT._Carsurin_1968.avif",
  },
  {
    id: "energi-selalu-baru",
    name: "PT Energi Selalu Baru",
    category: "energy",
    src: "/clients/energy/PT._Energi_Selalu_Baru_Logo.avif",
  },
  {
    id: "indonesia-evp-charger",
    name: "PT Indonesia EVP Charger",
    category: "energy",
    src: "/clients/energy/PT._Indonesia_EVP_Charger.avif",
  },
  {
    id: "kutai-refinery",
    name: "PT Kutai Refinery Nusantara",
    category: "energy",
    src: "/clients/energy/PT._Kutai_Refinery_Nusantara.avif",
  },
  {
    id: "terra-charge",
    name: "Terra Charge",
    category: "energy",
    src: "/clients/energy/Terra_Charge_Logo.avif",
  },
  {
    id: "trafindo",
    name: "Trafindo",
    category: "energy",
    src: "/clients/energy/Trafindo_Logo.avif",
  },
  {
    id: "utomo-charge",
    name: "UTOMO Charge+",
    category: "energy",
    src: "/clients/energy/UTOMO_Charge+_Logo.avif",
  },
  {
    id: "vale",
    name: "Vale",
    category: "energy",
    src: "/clients/energy/Vale_Logo.avif",
  },
  {
    id: "volta",
    name: "Volta",
    category: "energy",
    src: "/clients/energy/Volta_Logo.avif",
  },
  {
    id: "voltron",
    name: "Voltron",
    category: "energy",
    src: "/clients/energy/Voltron_Logo.avif",
  },

  {
    id: "angkasa-pura",
    name: "Angkasa Pura Airports",
    category: "government",
    src: "/clients/government/Angkasa_Pura_Airports.avif",
  },
  {
    id: "bumn",
    name: "BUMN Indonesia",
    category: "government",
    src: "/clients/government/bumn-indonesia-logo.avif",
  },
  {
    id: "dtkj",
    name: "DTKJ",
    category: "government",
    src: "/clients/government/DTKJ_Logo.avif",
  },
  {
    id: "hlf-msp",
    name: "HLF MSP Indonesia 2024",
    category: "government",
    src: "/clients/government/HLF_MSP_Indonesia_2024_Logo.avif",
  },
  {
    id: "iaf",
    name: "IAF",
    category: "government",
    src: "/clients/government/IAF_LOGO.avif",
  },
  {
    id: "tni-au",
    name: "Indonesian Airforce",
    category: "government",
    src: "/clients/government/Indonesian_Airforce_Swa_Bhuwana_Paksa_Logo.avif",
  },
  {
    id: "istana-ri",
    name: "Istana Kepresidenan RI",
    category: "government",
    src: "/clients/government/Istana_Kepresidenan_RI_Logo.avif",
  },
  {
    id: "tni-al",
    name: "Jalasveva Jayamahe (TNI AL)",
    category: "government",
    src: "/clients/government/Jalasveva_Jayamahe_Logo.avif",
  },
  {
    id: "jup-jakpro",
    name: "JUP by JakPro",
    category: "government",
    src: "/clients/government/JUP_by_JakPro_Logo.avif",
  },
  {
    id: "kemenhub",
    name: "Kementerian Perhubungan",
    category: "government",
    src: "/clients/government/Kementerian_Perhubungan_Republik_Indonesia-removebg-preview.avif",
  },
  {
    id: "kemensetneg",
    name: "Kementerian Sekretariat Negara",
    category: "government",
    src: "/clients/government/kementrian-seketariat-negara.avif",
  },
  {
    id: "polri",
    name: "POLRI",
    category: "government",
    src: "/clients/government/Kepolisian_Negara_Republik_Indonesia_Logo.avif",
  },
  {
    id: "knkt",
    name: "KNKT",
    category: "government",
    src: "/clients/government/KNKT_Logo.avif",
  },
  {
    id: "brimob",
    name: "KORPS BRIMOB",
    category: "government",
    src: "/clients/government/KORPS_BRIMOP_Logo.avif",
  },
  {
    id: "btkp",
    name: "BTKP",
    category: "government",
    src: "/clients/government/logo_btkp_new.avif",
  },
  {
    id: "paspampres",
    name: "Pasukan Pengamanan Presiden",
    category: "government",
    src: "/clients/government/Pasukan_Pengamanan_Presiden.avif",
  },
  {
    id: "pelni",
    name: "Pelni",
    category: "government",
    src: "/clients/government/Pelni_Logo.avif",
  },
  {
    id: "freeport",
    name: "PT Freeport Indonesia",
    category: "government",
    src: "/clients/government/PT_Freeport_Indonesia_Logo.avif",
  },
  {
    id: "pindad",
    name: "PT Pindad",
    category: "government",
    src: "/clients/government/PT_Pindad_Logo.avif",
  },
  {
    id: "haleyora-power",
    name: "PT Haleyora Power",
    category: "government",
    src: "/clients/government/PT._Haleyora_Power_Logo.avif",
  },
  {
    id: "pal-indonesia",
    name: "PT PAL Indonesia",
    category: "government",
    src: "/clients/government/PT._PAL_Indonesia.avif",
  },
  {
    id: "pupuk-iskandar-muda",
    name: "Pupuk Iskandar Muda",
    category: "government",
    src: "/clients/government/Pupuk_Iskandar_Muda_Aceh_Indonesia_Logo.avif",
  },
  {
    id: "tni",
    name: "TNI",
    category: "government",
    src: "/clients/government/Tentara_Nasional_Indonesia-logo-1E16A25DC7-seeklogo.com.avif",
  },

  {
    id: "ag-network",
    name: "AG Network",
    category: "private-sector",
    src: "/clients/private-sector/AG_Network_Logo.avif",
  },
  {
    id: "agung-sedayu",
    name: "Agung Sedayu Group",
    category: "private-sector",
    src: "/clients/private-sector/Agung_Sedayu_Group_Logo.avif",
  },
  {
    id: "alfamart",
    name: "Alfamart",
    category: "private-sector",
    src: "/clients/private-sector/ALFAMART_LOGO_BARU.avif",
  },
  {
    id: "april",
    name: "April",
    category: "private-sector",
    src: "/clients/private-sector/April_Logo.avif",
  },
  {
    id: "bank-indonesia",
    name: "Bank Indonesia",
    category: "private-sector",
    src: "/clients/private-sector/Bank_Indonesia_Logo.avif",
  },
  {
    id: "bank-mandiri",
    name: "Bank Mandiri",
    category: "private-sector",
    src: "/clients/private-sector/Bank_Mandiri_Logo.avif",
  },
  {
    id: "bca",
    name: "BCA Grup",
    category: "private-sector",
    src: "/clients/private-sector/BCA_Grup_Logo.avif",
  },
  {
    id: "beam",
    name: "Beam",
    category: "private-sector",
    src: "/clients/private-sector/Beam_Logo.avif",
  },
  {
    id: "brt",
    name: "Bintang Racing Team",
    category: "private-sector",
    src: "/clients/private-sector/Bintang_Racing_Team_Logo.avif",
  },
  {
    id: "bri",
    name: "Bank BRI",
    category: "private-sector",
    src: "/clients/private-sector/BRI_2020_Logo.svg.avif",
  },
  {
    id: "bumjin",
    name: "BUMJIN",
    category: "private-sector",
    src: "/clients/private-sector/BUMJIN_Logo.avif",
  },
  {
    id: "central-park",
    name: "Central Park",
    category: "private-sector",
    src: "/clients/private-sector/Central_Park_Logo.avif",
  },
  {
    id: "centre-park",
    name: "Centre Park",
    category: "private-sector",
    src: "/clients/private-sector/Centre_Park_Logo.avif",
  },
  {
    id: "chandra-asri",
    name: "Chandra Asri",
    category: "private-sector",
    src: "/clients/private-sector/Chandra_Asri_Logo.avif",
  },
  {
    id: "ciputra-world-jakarta",
    name: "Ciputra World Jakarta",
    category: "private-sector",
    src: "/clients/private-sector/Ciputra_World_Jakarta.avif",
  },
  {
    id: "ciputra-world-logo",
    name: "Ciputra World",
    category: "private-sector",
    src: "/clients/private-sector/Ciputra_World_Logo.avif",
  },
  {
    id: "danamon",
    name: "Danamon",
    category: "private-sector",
    src: "/clients/private-sector/Danamon_Logo.avif",
  },
  {
    id: "dharma-group",
    name: "Dharma Group",
    category: "private-sector",
    src: "/clients/private-sector/Dharma_Group_Logo.avif",
  },
  {
    id: "djarum",
    name: "Djarum",
    category: "private-sector",
    src: "/clients/private-sector/Djarum_Logo.avif",
  },
  {
    id: "eezee",
    name: "Eezee Technologies",
    category: "private-sector",
    src: "/clients/private-sector/Eezee_Technologies_Indonesia.avif",
  },
  {
    id: "excel-rim",
    name: "EXCEL Takasago Rim",
    category: "private-sector",
    src: "/clients/private-sector/EXCEL_Takasago_Rim_Logo.avif",
  },
  {
    id: "gandaria-city",
    name: "Gandaria City",
    category: "private-sector",
    src: "/clients/private-sector/Gandaria_City_Logo.avif",
  },
  {
    id: "gramedia",
    name: "Gramedia",
    category: "private-sector",
    src: "/clients/private-sector/Gramedia_Logo.svg.avif",
  },
  {
    id: "green-pramuka",
    name: "Green Pramuka City",
    category: "private-sector",
    src: "/clients/private-sector/Green_Pramuka_City_Logo.avif",
  },
  {
    id: "gudang-garam",
    name: "Gudang Garam",
    category: "private-sector",
    src: "/clients/private-sector/Gudang_Garam_Logo.avif",
  },
  {
    id: "indofood",
    name: "Indofood CBP",
    category: "private-sector",
    src: "/clients/private-sector/Indofood_CBP_Logo.avif",
  },
  {
    id: "indomaret",
    name: "Indomaret",
    category: "private-sector",
    src: "/clients/private-sector/Indomaret_Logo.avif",
  },
  {
    id: "jakarta-notebook",
    name: "Jakarta Notebook",
    category: "private-sector",
    src: "/clients/private-sector/Jakarta_Notebook_Logo.avif",
  },
  {
    id: "jaya-kelola",
    name: "Jaya Kelola",
    category: "private-sector",
    src: "/clients/private-sector/Jaya_Kelola_Logo.avif",
  },
  {
    id: "koleksi",
    name: "KOLEKSI",
    category: "private-sector",
    src: "/clients/private-sector/KOLEKSI_logo.avif",
  },
  {
    id: "kosmik",
    name: "Kosmik",
    category: "private-sector",
    src: "/clients/private-sector/kosmik.avif",
  },
  {
    id: "kuningan-city",
    name: "Kuningan City",
    category: "private-sector",
    src: "/clients/private-sector/Kuningan_City_Logo_2.avif",
  },
  {
    id: "lippo",
    name: "Lippo Group",
    category: "private-sector",
    src: "/clients/private-sector/Lippo_Group_Logo.svg.avif",
  },
  {
    id: "pondok-indah-mall",
    name: "Mall Pondok Indah",
    category: "private-sector",
    src: "/clients/private-sector/Mall_Pondok_Indah_logo.avif",
  },
  {
    id: "motomobi",
    name: "Motomobi TV",
    category: "private-sector",
    src: "/clients/private-sector/Motomobi_TV.avif",
  },
  {
    id: "mvp",
    name: "Multivision Plus",
    category: "private-sector",
    src: "/clients/private-sector/Multivision_Plus_MVP_Logo.avif",
  },
  {
    id: "neo-soho",
    name: "Neo Soho",
    category: "private-sector",
    src: "/clients/private-sector/Neo_Soho_Logo.avif",
  },
  {
    id: "oic-city",
    name: "OIC City Neon",
    category: "private-sector",
    src: "/clients/private-sector/OIC_City_Neon_Logo.avif",
  },
  {
    id: "optik-seis",
    name: "Optik Seis",
    category: "private-sector",
    src: "/clients/private-sector/Optik_Seis_Logo.avif",
  },
  {
    id: "pacific-place",
    name: "Pacific Place",
    category: "private-sector",
    src: "/clients/private-sector/Pacific_Place_Logo.avif",
  },
  {
    id: "panasonic",
    name: "Panasonic",
    category: "private-sector",
    src: "/clients/private-sector/Panasonic-logo.avif",
  },
  {
    id: "pikko-group",
    name: "Pikko Group",
    category: "private-sector",
    src: "/clients/private-sector/Pikko_Group_Logo.avif",
  },
  {
    id: "plaza-indonesia",
    name: "Plaza Indonesia",
    category: "private-sector",
    src: "/clients/private-sector/Plaza_Indonesia_Logo.avif",
  },
  {
    id: "plaza-senayan",
    name: "Plaza Senayan",
    category: "private-sector",
    src: "/clients/private-sector/Plaza_Senayan_Logo.avif",
  },
  {
    id: "polygon",
    name: "Polygon Bikes",
    category: "private-sector",
    src: "/clients/private-sector/Polygon_Bikes_Logo.avif",
  },
  {
    id: "pondok-indah",
    name: "Pondok Indah",
    category: "private-sector",
    src: "/clients/private-sector/Pondok_Indah_Logo.avif",
  },
  {
    id: "prudential",
    name: "Prudential",
    category: "private-sector",
    src: "/clients/private-sector/Prudential_Logo.avif",
  },
  {
    id: "alumunium-alloy",
    name: "PT Alumunium Alloy Abadi",
    category: "private-sector",
    src: "/clients/private-sector/PT_Alumunium_Alloy_Abadi.avif",
  },
  {
    id: "citra-sanxing",
    name: "PT Citra Sanxing Indonesia",
    category: "private-sector",
    src: "/clients/private-sector/PT_Citra_Sanxing_Indonesia.avif",
  },
  {
    id: "dharma-protindo",
    name: "PT Dharma Protindo Karya",
    category: "private-sector",
    src: "/clients/private-sector/PT_Dharma_Protindo_Karya.avif",
  },
  {
    id: "multiprima",
    name: "PT Multiprima Indosejahtera",
    category: "private-sector",
    src: "/clients/private-sector/PT_Multiprima_Indosejahtera_Logo.avif",
  },
  {
    id: "bitwyre",
    name: "PT Teknologi Struktur Berantai Bitwyre",
    category: "private-sector",
    src: "/clients/private-sector/PT_Teknologi_Struktur_Berantai_Bitwyre.avif",
  },
  {
    id: "tugu-reasuransi",
    name: "PT Tugu Reasuransi Indonesia",
    category: "private-sector",
    src: "/clients/private-sector/PT_Tugu_Reasuransi_Indonesia.avif",
  },
  {
    id: "kianis-pratama",
    name: "PT Kianis Pratama",
    category: "private-sector",
    src: "/clients/private-sector/PT._Kianis_Pratama_Logo.avif",
  },
  {
    id: "lautan-luas",
    name: "PT Lautan Luas Tbk",
    category: "private-sector",
    src: "/clients/private-sector/PT._Lautan_Luas_Tbk.avif",
  },
  {
    id: "sango-ceramics",
    name: "PT Sango Ceramics",
    category: "private-sector",
    src: "/clients/private-sector/PT._Sango_Ceramics.avif",
  },
  {
    id: "solusi-intek",
    name: "PT Solusi Intek Indonesia",
    category: "private-sector",
    src: "/clients/private-sector/PT._Solusi_Intek_Indonesia.avif",
  },
  {
    id: "victoria-care",
    name: "PT Victoria Care Indonesia",
    category: "private-sector",
    src: "/clients/private-sector/PT._Victoria_Care_Indonesia_Logo.avif",
  },
  {
    id: "puri-indah-mall",
    name: "Puri Indah Mall",
    category: "private-sector",
    src: "/clients/private-sector/Puri_Indah_Mall_Logo.avif",
  },
  {
    id: "samjin",
    name: "SAMJIN",
    category: "private-sector",
    src: "/clients/private-sector/SAMJIN_Logo.avif",
  },
  {
    id: "satria-group",
    name: "Satria Group",
    category: "private-sector",
    src: "/clients/private-sector/Satria_Group_Logo.avif",
  },
  {
    id: "satria-piranti",
    name: "Satria Piranti Perkasa",
    category: "private-sector",
    src: "/clients/private-sector/Satria_Piranti_Perkasa_Logo.avif",
  },
  {
    id: "senayan-city",
    name: "Senayan City",
    category: "private-sector",
    src: "/clients/private-sector/Senayan_City_Logo.avif",
  },
  {
    id: "sequis",
    name: "Sequis",
    category: "private-sector",
    src: "/clients/private-sector/Sequis_Logo.avif",
  },
  {
    id: "siloam",
    name: "Siloam Hospitals",
    category: "private-sector",
    src: "/clients/private-sector/Siloam_Hospitals_Logo.avif",
  },
  {
    id: "sinarmas",
    name: "Sinarmas",
    category: "private-sector",
    src: "/clients/private-sector/Sinarmas_Logo.avif",
  },
  {
    id: "smartfren",
    name: "Smartfren",
    category: "private-sector",
    src: "/clients/private-sector/Smartfren_Logo.avif",
  },
  {
    id: "sungai-budi",
    name: "Sungai Budi Group",
    category: "private-sector",
    src: "/clients/private-sector/Sungai_Budi_Group.avif",
  },
  {
    id: "tata-aia",
    name: "TATA AIA LIFE",
    category: "private-sector",
    src: "/clients/private-sector/TATA_AIA_LIFE_LOGO.avif",
  },
  {
    id: "tcs",
    name: "TCS Asia Pacific",
    category: "private-sector",
    src: "/clients/private-sector/TCS_Asia_Pacific_Indonesia_Logo.avif",
  },
  {
    id: "telin",
    name: "Telin",
    category: "private-sector",
    src: "/clients/private-sector/Telin_company_logo.avif",
  },
  {
    id: "tempo-scan",
    name: "Tempo Scan",
    category: "private-sector",
    src: "/clients/private-sector/Tempo_Scan_Logo.svg.avif",
  },
  {
    id: "uob",
    name: "UOB",
    category: "private-sector",
    src: "/clients/private-sector/UOB_Logo.avif",
  },

  {
    id: "1001-hotel",
    name: "1001 Hotel",
    category: "property",
    src: "/clients/property/1001_Hotel_Logo.avif",
  },
  {
    id: "18-office-park",
    name: "18 Office Park",
    category: "property",
    src: "/clients/property/18_Office_Park_Logo_2.avif",
  },
  {
    id: "57-thamrin",
    name: "5ifty7even Thamrin",
    category: "property",
    src: "/clients/property/5ifty7even_Thamrin_Promenade_Logo_(2).avif",
  },
  {
    id: "9-residence",
    name: "9+ Residence",
    category: "property",
    src: "/clients/property/9+Residence+Logo.avif",
  },
  {
    id: "aia",
    name: "AIA",
    category: "property",
    src: "/clients/property/AIA_Logo.avif",
  },
  {
    id: "archipelago",
    name: "Archipelago International",
    category: "property",
    src: "/clients/property/Archipelago_International_Logo.avif",
  },
  {
    id: "arkadia",
    name: "Arkadia Green Park",
    category: "property",
    src: "/clients/property/Arkadia_Green_Park.avif",
  },
  {
    id: "ascott",
    name: "Ascott Jakarta",
    category: "property",
    src: "/clients/property/Ascott_Jakarta_Logo.avif",
  },
  {
    id: "bakrieland",
    name: "Bakrieland",
    category: "property",
    src: "/clients/property/Bakrieland_Logo.avif",
  },
  {
    id: "batavia-apartments",
    name: "Batavia Apartments",
    category: "property",
    src: "/clients/property/Batavia_Apartments.avif",
  },
  {
    id: "branz-bsd",
    name: "Branz BSD",
    category: "property",
    src: "/clients/property/Branz_BSD_Logo.avif",
  },
  {
    id: "bumi-daya-plaza",
    name: "Bumi Daya Plaza",
    category: "property",
    src: "/clients/property/Bumi_Daya_Plaza_Logo.avif",
  },
  {
    id: "capital-place",
    name: "Capital Place",
    category: "property",
    src: "/clients/property/Capital_Place_Logo.avif",
  },
  {
    id: "casa-grande",
    name: "Casa Grande Residence",
    category: "property",
    src: "/clients/property/Casa_Grande_Residence_Logo.avif",
  },
  {
    id: "centennial-towers",
    name: "Centennial Towers",
    category: "property",
    src: "/clients/property/Centennial_Towers_Logo.avif",
  },
  {
    id: "chillax",
    name: "Chillax",
    category: "property",
    src: "/clients/property/Chillax_Logo.avif",
  },
  {
    id: "ciputra-world-surabaya",
    name: "Ciputra World Surabaya",
    category: "property",
    src: "/clients/property/Ciputra_World_Surabaya_Logo.avif",
  },
  {
    id: "crest-vista",
    name: "Crest Vista",
    category: "property",
    src: "/clients/property/Crest_Vista_Logo.avif",
  },
  {
    id: "embarcadero",
    name: "Embarcadero Bintaro",
    category: "property",
    src: "/clients/property/Embarcadero_Bintaro_Logo-removebg-preview.avif",
  },
  {
    id: "emporium-pluit",
    name: "Emporium Pluit",
    category: "property",
    src: "/clients/property/Emporium_Pluit_Logo.avif",
  },
  {
    id: "essence-darmawangsa",
    name: "Essence Darmawangsa",
    category: "property",
    src: "/clients/property/Essence_Darmawangsa_Logo.avif",
  },
  {
    id: "gbi-ecclesia",
    name: "GBI Ecclesia Ministry",
    category: "property",
    src: "/clients/property/GBI_Ecclesia_Ministry_Logo.avif",
  },
  {
    id: "gold-coast",
    name: "Gold Coast Sea View",
    category: "property",
    src: "/clients/property/Gold_Coast_Sea_View_Apartment_&_Office_Logo.avif",
  },
  {
    id: "holland-village",
    name: "Holland Village Jakarta",
    category: "property",
    src: "/clients/property/Holland_Village_Jakarta_Logo.avif",
  },
  {
    id: "hquarters",
    name: "Hquarters",
    category: "property",
    src: "/clients/property/Hquarters_Logo.avif",
  },
  {
    id: "ifc-tower",
    name: "IFC Tower Jakarta",
    category: "property",
    src: "/clients/property/IFC_Tower_Jakarta_Logo.avif",
  },
  {
    id: "indogrosir",
    name: "Indogrosir",
    category: "property",
    src: "/clients/property/Indogrosir_Logo.avif",
  },
  {
    id: "intiland",
    name: "Intiland",
    category: "property",
    src: "/clients/property/Intiland_Logo.svg.avif",
  },
  {
    id: "kem-tower",
    name: "KEM Tower",
    category: "property",
    src: "/clients/property/KEM_Tower_Logo.avif",
  },
  {
    id: "lavie-suites",
    name: "Lavie All Suites",
    category: "property",
    src: "/clients/property/Lavie_All_Suites_Apartment_Logo.avif",
  },
  {
    id: "margo-city",
    name: "Margo City",
    category: "property",
    src: "/clients/property/Margo_City_Logo.avif",
  },
  {
    id: "menara-astra",
    name: "Menara Astra",
    category: "property",
    src: "/clients/property/Menara_Astra_Logo.avif",
  },
  {
    id: "menara-batavia",
    name: "Menara Batavia",
    category: "property",
    src: "/clients/property/Menara_Batavia_Logo.avif",
  },
  {
    id: "menteng-park-emerald",
    name: "Menteng Park Emerald",
    category: "property",
    src: "/clients/property/Menteng_Park_Exclusive_Emerald_Residence_Logo.avif",
  },
  {
    id: "menteng-park",
    name: "Menteng Park Residence",
    category: "property",
    src: "/clients/property/Menteng_Park_Residence_Logo.avif",
  },
  {
    id: "mercure",
    name: "Mercure Hotels",
    category: "property",
    src: "/clients/property/Mercure_Hotels_Logo.avif",
  },
  {
    id: "osaka-riverview",
    name: "Osaka Riverview",
    category: "property",
    src: "/clients/property/Osaka_Riverview_Apartment_Logo.avif",
  },
  {
    id: "pakuwon",
    name: "Pakuwon Group",
    category: "property",
    src: "/clients/property/Pakuwon_Group_Logo.avif",
  },
  {
    id: "pakuwon-mall-jogja",
    name: "Pakuwon Mall Jogja",
    category: "property",
    src: "/clients/property/Pakuwon_Mall_Jogja.avif",
  },
  {
    id: "casablanca",
    name: "PPPSRS Casablanca",
    category: "property",
    src: "/clients/property/PPPSRS_Casablanca.avif",
  },
  {
    id: "capital-residence",
    name: "The Capital Residence",
    category: "property",
    src: "/clients/property/PPPSRS_The_Capital_Residence_Logo.avif",
  },
  {
    id: "pavilion-apartment",
    name: "PPRS Pavilion Apartment",
    category: "property",
    src: "/clients/property/PPRS_Pavilion_Apartment.avif",
  },
  {
    id: "providence-park",
    name: "Providence Park",
    category: "property",
    src: "/clients/property/Providence_Park_Logo.avif",
  },
  {
    id: "pakuwon-jati",
    name: "PT Pakuwon Jati Tbk",
    category: "property",
    src: "/clients/property/PT_Pakuwon_Jati_Tbk.avif",
  },
  {
    id: "aca",
    name: "PT ACA",
    category: "property",
    src: "/clients/property/PT._ACA_Logo.avif",
  },
  {
    id: "estika-yasakelola",
    name: "PT Estika Yasakelola",
    category: "property",
    src: "/clients/property/PT._Estika_Yasakelola_Logo.avif",
  },
  {
    id: "pakuwon-residences-bekasi",
    name: "Pakuwon Residences Bekasi",
    category: "property",
    src: "/clients/property/PT._Grama_Pramesi_Siddhi_[Pakuwon_Residences_Bekasi]_Logo.avif",
  },
  {
    id: "metropolitan-dev",
    name: "PT Metropolitan Development",
    category: "property",
    src: "/clients/property/PT._Metropolitan_Development_Logo.avif",
  },
  {
    id: "permata-birama",
    name: "PT Permata Birama Sakti",
    category: "property",
    src: "/clients/property/PT._Permata_Birama_Sakti_Logo.avif",
  },
  {
    id: "primasta",
    name: "PT Prima Adicipta Gunatama",
    category: "property",
    src: "/clients/property/PT._Prima_Adicipta_Gunatama_[Primasta]_Logo.avif",
  },
  {
    id: "puri-pesona",
    name: "PT Puri Pesona Properti",
    category: "property",
    src: "/clients/property/PT._Puri_Pesona_Properti_Logo.avif",
  },
  {
    id: "wiratama-indo",
    name: "PT Wiratama Indo Nusantara",
    category: "property",
    src: "/clients/property/PT._Wiratama_Indo_Nusantara.avif",
  },
  {
    id: "lavie-zaman",
    name: "PT Zaman Bangun Perwita",
    category: "property",
    src: "/clients/property/PT._Zaman_Bangun_Perwita_[Lavie]_Logo.avif",
  },
  {
    id: "pullman",
    name: "Pullman Hotels",
    category: "property",
    src: "/clients/property/Pullman_Hotels_&_Resorts_Logo.avif",
  },
  {
    id: "raffles",
    name: "Raffles Jakarta",
    category: "property",
    src: "/clients/property/Raffles_Jakarta_Logo.avif",
  },
  {
    id: "rainbow-spring-villas",
    name: "Rainbow Spring Condo Villas",
    category: "property",
    src: "/clients/property/Rainbow_Spring_Condo_Villas_Summarecon_Logo.avif",
  },
  {
    id: "regatta-jakarta",
    name: "Regatta Jakarta",
    category: "property",
    src: "/clients/property/Regatta_Jakarta_Logo.avif",
  },
  {
    id: "regent-residence",
    name: "Regent Residence",
    category: "property",
    src: "/clients/property/Regent_Residence_Jakarta.avif",
  },
  {
    id: "residence-8",
    name: "Residence 8 Senopati",
    category: "property",
    src: "/clients/property/Residence_8_Senopati_Logo.avif",
  },
  {
    id: "riverview-residence",
    name: "Riverview Residence",
    category: "property",
    src: "/clients/property/Riverview_Residence_Logo.avif",
  },
  {
    id: "sahid-sudirman",
    name: "Sahid Sudirman Center",
    category: "property",
    src: "/clients/property/Sahid_Sudirman_Center_Logo.avif",
  },
  {
    id: "sedayu-city",
    name: "Sedayu City",
    category: "property",
    src: "/clients/property/Sedayu_City_Kelapa_Gading.avif",
  },
  {
    id: "senayan-park",
    name: "Senayan Park",
    category: "property",
    src: "/clients/property/Senayan_Park_Logo.avif",
  },
  {
    id: "sequis-center",
    name: "SEQUIS CENTER",
    category: "property",
    src: "/clients/property/SEQUIS_CENTER_LOGO.avif",
  },
  {
    id: "shangri-la",
    name: "Shangri-La",
    category: "property",
    src: "/clients/property/Shangri-La_Logo.avif",
  },
  {
    id: "shn",
    name: "SHN",
    category: "property",
    src: "/clients/property/SHN_LOGO.avif",
  },
  {
    id: "signature-park",
    name: "Signature Park Grande",
    category: "property",
    src: "/clients/property/Signature_Park_Grance.avif",
  },
  {
    id: "somerset",
    name: "Somerset",
    category: "property",
    src: "/clients/property/Somerset_Logo.avif",
  },
  {
    id: "spazio-tower",
    name: "Spazio Tower",
    category: "property",
    src: "/clients/property/Spazio_Tower.avif",
  },
  {
    id: "south-quarter",
    name: "SQ South Quarter",
    category: "property",
    src: "/clients/property/SQ_South_Quarter_Logo.avif",
  },
  {
    id: "st-moritz",
    name: "St. Moritz",
    category: "property",
    src: "/clients/property/St._Moritz_Logo.avif",
  },
  {
    id: "st-regis",
    name: "ST. REGIS",
    category: "property",
    src: "/clients/property/ST._REGIS_Logo.avif",
  },
  {
    id: "summarecon-serpong",
    name: "Summarecon Serpong",
    category: "property",
    src: "/clients/property/Summarecon_Serpong_Logo.avif",
  },
  {
    id: "suvarna-golf",
    name: "Suvarna Jakarta Gold Club",
    category: "property",
    src: "/clients/property/Suvarna_Jakarta_Gold_Club_Logo.avif",
  },
  {
    id: "talavera",
    name: "Talavera Office Park",
    category: "property",
    src: "/clients/property/Talavera_Office_Park_Logo.avif",
  },
  {
    id: "taman-anggrek",
    name: "Taman Anggrek Residences",
    category: "property",
    src: "/clients/property/Taman_Anggrek_Residences_Logo.avif",
  },
  {
    id: "the-bellezza",
    name: "The Bellezza",
    category: "property",
    src: "/clients/property/The_Bellezza.avif",
  },
  {
    id: "city-tower-hotel",
    name: "The City Tower Hotel",
    category: "property",
    src: "/clients/property/The_City_Tower_Hotel.avif",
  },
  {
    id: "darmawangsa-square",
    name: "The Darmawangsa Square",
    category: "property",
    src: "/clients/property/The_Darmawangsa_Square_Logo.avif",
  },
  {
    id: "the-dharmawangsa",
    name: "The Dharmawangsa",
    category: "property",
    src: "/clients/property/The_Dharmawangsa_Logo.avif",
  },
  {
    id: "the-elements",
    name: "The Elements Luxury Living",
    category: "property",
    src: "/clients/property/The_Elements_Luxury_Living_Logo.avif",
  },
  {
    id: "grand-mansion",
    name: "The Grand Mansion Menteng",
    category: "property",
    src: "/clients/property/The_Grand_Mansion_Menteng.avif",
  },
  {
    id: "pakubuwono",
    name: "The Pakubuwono Residence",
    category: "property",
    src: "/clients/property/The_Pakubuwono_Residence_Logo.avif",
  },
  {
    id: "peal-sudirman",
    name: "The PEAL at Sudirman",
    category: "property",
    src: "/clients/property/The_PEAL_at_Sudirman_Logo.avif",
  },
  {
    id: "windsor-residence",
    name: "The Windsor Residence",
    category: "property",
    src: "/clients/property/The_Windsor_Residence_Logo.avif",
  },
  {
    id: "tm-agung-podomoro",
    name: "TM Agung Podomoro",
    category: "property",
    src: "/clients/property/TM_Agung_Podomoro_Logo.avif",
  },
  {
    id: "tokyo-riverside",
    name: "Tokyo Riverside Apartment",
    category: "property",
    src: "/clients/property/Tokyo_Riverside_Apartment_PIK2Logo.avif",
  },
  {
    id: "trembesi-tower",
    name: "Trembesi Tower & Hotel",
    category: "property",
    src: "/clients/property/Trembesi_Tower_&_Hotel_Logo_2.avif",
  },
  {
    id: "trump-golf-lido",
    name: "Trump International Golf Lido",
    category: "property",
    src: "/clients/property/Trump_International_Golf_Lido_Logo.avif",
  },
  {
    id: "vimala-hills",
    name: "Vimala Hills",
    category: "property",
    src: "/clients/property/Vimala_Hills_Logo.avif",
  },
  {
    id: "west-vista",
    name: "West Vista",
    category: "property",
    src: "/clients/property/West_Vista_Logo.avif",
  },
  {
    id: "wtc",
    name: "World Trade Center",
    category: "property",
    src: "/clients/property/World_Trade_Center_Logo.avif",
  },

  {
    id: "toyota-astra",
    name: "Astra Toyota Astra Motor",
    category: "transportation",
    src: "/clients/transportation/Astra_-_Toyota_Astra_Motor.avif",
  },
  {
    id: "daihatsu-astra",
    name: "Astra Daihatsu",
    category: "transportation",
    src: "/clients/transportation/Astra_Daihatsu__Logo.avif",
  },
  {
    id: "ahm",
    name: "Astra Honda Motor",
    category: "transportation",
    src: "/clients/transportation/Astra_Honta_Motor_[AHM].avif",
  },
  {
    id: "astra-otoparts",
    name: "Astra Otoparts",
    category: "transportation",
    src: "/clients/transportation/Astra_Otoparts.avif",
  },
  {
    id: "benelli-1",
    name: "Benelli",
    category: "transportation",
    src: "/clients/transportation/Benelli.avif",
  },
  {
    id: "bluebird",
    name: "Bluebird",
    category: "transportation",
    src: "/clients/transportation/Bluebird_Logogram.avif",
  },
  {
    id: "bmw",
    name: "BMW",
    category: "transportation",
    src: "/clients/transportation/BMW.avif",
  },
  {
    id: "ceojetset",
    name: "Ceojetset",
    category: "transportation",
    src: "/clients/transportation/Ceojetset_Logo.avif",
  },
  {
    id: "ssktama",
    name: "SSKTama",
    category: "transportation",
    src: "/clients/transportation/cropped-SSKTama-Logo-2023-scaled-1-removebg-preview.avif",
  },
  {
    id: "daihatsu",
    name: "Daihatsu",
    category: "transportation",
    src: "/clients/transportation/Daihatsu.avif",
  },
  {
    id: "dfsk",
    name: "DFSK",
    category: "transportation",
    src: "/clients/transportation/DFSK.avif",
  },
  {
    id: "dhl",
    name: "DHL",
    category: "transportation",
    src: "/clients/transportation/DHL.avif",
  },
  {
    id: "eurokars",
    name: "Eurokars Group",
    category: "transportation",
    src: "/clients/transportation/Eurokars_Group_Logo.avif",
  },
  {
    id: "foton",
    name: "Foton",
    category: "transportation",
    src: "/clients/transportation/Foton.avif",
  },
  {
    id: "lexus",
    name: "LEXUS",
    category: "transportation",
    src: "/clients/transportation/LEXUS.avif",
  },
  {
    id: "mitsubishi",
    name: "Mitsubishi",
    category: "transportation",
    src: "/clients/transportation/Mitsubishi.avif",
  },
  {
    id: "mobil-tm",
    name: "MobilTM",
    category: "transportation",
    src: "/clients/transportation/MobilTM.avif",
  },
  {
    id: "porsche",
    name: "Porsche",
    category: "transportation",
    src: "/clients/transportation/Porsche_Logo.svg.avif",
  },
  {
    id: "prima-armada",
    name: "Prima Armada Raya",
    category: "transportation",
    src: "/clients/transportation/Prima_Armada_Raya_logo.avif",
  },
  {
    id: "bahagia-audio",
    name: "PT Bahagia Audio Video",
    category: "transportation",
    src: "/clients/transportation/PT_Bahagia_Audio_Video.avif",
  },
  {
    id: "estika-yasakelola-trans",
    name: "PT Estika Yasakelola",
    category: "transportation",
    src: "/clients/transportation/PT_Estika_Yasakelola.avif",
  },
  {
    id: "intan-angkasa",
    name: "PT Intan Angkasa Air Service",
    category: "transportation",
    src: "/clients/transportation/PT_Intan_Angkasa_Air_Service.avif",
  },
  {
    id: "fajar-bahari",
    name: "PT Fajar Bahari Nusantara",
    category: "transportation",
    src: "/clients/transportation/PT._Fajar_Bahari_Nusantara.avif",
  },
  {
    id: "keeway-emotor",
    name: "PT Keeway Emotor Indonesia",
    category: "transportation",
    src: "/clients/transportation/PT._Keeway_Emotor_Indonesia.avif",
  },
  {
    id: "puninar",
    name: "Puninar Logistics",
    category: "transportation",
    src: "/clients/transportation/Puninar_Logistics_Logo_2.avif",
  },
  {
    id: "suzuki",
    name: "Suzuki",
    category: "transportation",
    src: "/clients/transportation/Suzuki.svg.avif",
  },
  {
    id: "tda-luxury",
    name: "TDA Luxury Toys",
    category: "transportation",
    src: "/clients/transportation/TDA_Luxury_Toys_Logo.avif",
  },
  {
    id: "tekno-repair",
    name: "Tekno Body Repair",
    category: "transportation",
    src: "/clients/transportation/Tekno_Body_Repair_Logo.avif",
  },
  {
    id: "xpeng",
    name: "XPeng",
    category: "transportation",
    src: "/clients/transportation/XPeng.avif",
  },
  {
    id: "yusen-logistics",
    name: "Yusen Logistics",
    category: "transportation",
    src: "/clients/transportation/Yusen_Logistics.avif",
  },
];
